### ISSUE TITLE
Morning session: peer-to-peer code review

### ISSUE THREAD

**Issue by Malcom-Charlie** [NicolasAndrehh/Awesome-Books#7]
## Good work all project requirements achieved.
However, there are a few suggestions that we would like to recommend:
- Add some code to ensure the add books section is cleared after adding a book.
- Consider removing the required attribute in your inputs, as you already have code to catch the error
- Edit the ReadMe title to match this project.
-  Recommend adding an overflow and set to scroll for the booklist.

**Comment by NicolasAndrehh** [comment]
## Issues solved
Hey @Malcom-Charlie, thank you for your feedback, I already implement the changes that you suggested, on the last pull request.
